\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={A4},
            pdfauthor={Zoe Zhou},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{A4}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Zoe Zhou}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{11/05/2020}


\begin{document}
\maketitle

\hypertarget{ts1}{%
\paragraph{TS1:}\label{ts1}}

\hypertarget{i}{%
\paragraph{(i)}\label{i}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot.ts}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS1, }\DataTypeTok{main =} \StringTok{"Time Series 1"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{acf}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS1, }\DataTypeTok{main =} \StringTok{"ACF plot for TS1"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-2-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pacf}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS1, }\DataTypeTok{main =} \StringTok{"PACF plot for TS1"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-2-3.pdf}

\hypertarget{ii}{%
\paragraph{(ii)}\label{ii}}

Model：\(y_t = \rho_1y_{t-1} + \rho_2y_{t-2} + \epsilon_t\)

The most appropriate model will be a AR(2). From the series we can see
strong clustering pattern which means we have positive autocorrelation
in the series. The plot of ACF showed decay and PACF showed a cutoff at
2 lags.

\hypertarget{iii}{%
\paragraph{(iii)}\label{iii}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{TS1.fit =}\StringTok{ }\KeywordTok{arima}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS1, }\DataTypeTok{order =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{))}
\NormalTok{TS1.fit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## arima(x = all$TS1, order = c(2, 0, 0))
## 
## Coefficients:
##          ar1     ar2  intercept
##       0.5958  0.2928     0.2106
## s.e.  0.0302  0.0303     0.2821
## 
## sigma^2 estimated as 1.008:  log likelihood = -1423.72,  aic = 2855.44
\end{verbatim}

Model：\(y_t = 0.5958y_{t-1} + 0.2928y_{t-2} + \epsilon_t\)

\hypertarget{iv}{%
\paragraph{(iv)}\label{iv}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot.ts}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS1.fit), }\DataTypeTok{main =} \StringTok{"Residual Series for TS1"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{acf}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS1.fit))}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-4-2.pdf}

\hypertarget{comments}{%
\paragraph{Comments:}\label{comments}}

The residual series seemed to follow a normal distribution with a mean
around 0. The variance are reasonably constant. The plot of ACF of the
residuals showed no problems. All autocorrelation had been modeled.

\hypertarget{v}{%
\paragraph{(v)}\label{v}}

Other models: ARMA(1, 1) AIC = 2863.19

AR(3) AIC = 2857.43, the 3rd AR term is not significant.

ARMA(1, 2) AIC = 2858.79

ARMA(2, 1) AIC = 2857.43, the 1st MA term is not significant

The AR(2) model had the smallest AIC (2855.44) and all terms are
significant.

\hypertarget{ts2}{%
\paragraph{TS2:}\label{ts2}}

\hypertarget{i-1}{%
\paragraph{(i)}\label{i-1}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot.ts}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS2, }\DataTypeTok{main =} \StringTok{"Time Series 2"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{acf}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS2, }\DataTypeTok{main =} \StringTok{"ACF plot for TS2"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-5-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pacf}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS2, }\DataTypeTok{main =} \StringTok{"PACF plot for TS2"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-5-3.pdf}

\hypertarget{ii-1}{%
\paragraph{(ii)}\label{ii-1}}

Model：\(y_t = \rho_1y_{t-1} + \epsilon_t+ \alpha_1\epsilon_{t-1}\)

The most appropriate model will be ARMA(1,1). From the series we can see
strong clustering pattern which means we have autocorrelation in the
series. The plot of ACF showed decay and PACF also showed decay or some
persistence. Since we don't know the order for the model we can start
trying with ARMA(1,1).

\hypertarget{iii-1}{%
\paragraph{(iii)}\label{iii-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{TS2.fit =}\StringTok{ }\KeywordTok{arima}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS2, }\DataTypeTok{order =} \KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\NormalTok{TS2.fit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## arima(x = all$TS2, order = c(1, 0, 1))
## 
## Coefficients:
##           ar1     ma1  intercept
##       -0.3504  0.8459    -0.0084
## s.e.   0.0403  0.0219     0.0531
## 
## sigma^2 estimated as 1.509:  log likelihood = -1624.86,  aic = 3257.73
\end{verbatim}

Model：\(y_t = -0.3504y_{t-1} + \epsilon_t + 0.8459\epsilon_{t-1}\)

\hypertarget{iv-1}{%
\paragraph{(iv)}\label{iv-1}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot.ts}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS2.fit), }\DataTypeTok{main =} \StringTok{"Residual Series"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{acf}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS2.fit))}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-7-2.pdf}

\hypertarget{comments-1}{%
\paragraph{Comments:}\label{comments-1}}

The residual series seemed to follow a normal distribution with a mean
around 0. The variance are reasonably constant. The plot of ACF of the
residuals showed we still have 2 significant lags at lag(2) and lag(4).

\hypertarget{v-1}{%
\paragraph{(v)}\label{v-1}}

Better model:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# ARMA(2, 1)}
\NormalTok{TS2.fit2 =}\StringTok{ }\KeywordTok{arima}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS2, }\DataTypeTok{order =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\NormalTok{TS2.fit2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## arima(x = all$TS2, order = c(2, 0, 1))
## 
## Coefficients:
##           ar1      ar2     ma1  intercept
##       -0.2975  -0.1888  0.7471    -0.0088
## s.e.   0.0490   0.0387  0.0427     0.0451
## 
## sigma^2 estimated as 1.474:  log likelihood = -1613.16,  aic = 3236.32
\end{verbatim}

ARMA(2, 1) AIC = 3236.32

Model：\(y_t = -0.2975y_{t-1} + -0.1888y_{t-1} + \epsilon_t + 0.7471\epsilon_{t-1}\)

The ARMA(2, 1) model has the smallest AIC (3236.32) and all terms are
significant.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot.ts}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS2.fit2), }\DataTypeTok{main=}\StringTok{"Residual Series"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-9-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{acf}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS2.fit2))}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-9-2.pdf}

\hypertarget{comments-2}{%
\paragraph{Comments:}\label{comments-2}}

The residual series seemed to follow a normal distribution with a mean
around 0. The variance are reasonably constant. The plot of ACF of the
residuals showed lag(9) is slightly significant but it is very weak and
not of concern.

\hypertarget{ts3}{%
\paragraph{TS3:}\label{ts3}}

\hypertarget{i-2}{%
\paragraph{(i)}\label{i-2}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot.ts}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS3, }\DataTypeTok{main =} \StringTok{"Time Series 3"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{acf}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS3, }\DataTypeTok{main =} \StringTok{"ACF plot for TS3"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-10-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pacf}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS3, }\DataTypeTok{main =} \StringTok{"PACF plot for TS3"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-10-3.pdf}

\hypertarget{ii-2}{%
\paragraph{(ii)}\label{ii-2}}

Model：\(y_t = \epsilon_t\)

The most appropriate model will be a White noise. From the series we
cannot really see much pattern happening. The variance seemed very
constant and the series has an overall mean around 0. The plot of ACF
showed no significant lags and the plot of PACF showed no significant
lags as well. This series should be a white noise.

\hypertarget{iii-2}{%
\paragraph{(iii)}\label{iii-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{TS3.fit =}\StringTok{ }\KeywordTok{arima}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS3, }\DataTypeTok{order =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{))}
\NormalTok{TS3.fit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## arima(x = all$TS3, order = c(0, 0, 0))
## 
## Coefficients:
##       intercept
##          0.0211
## s.e.     0.0316
## 
## sigma^2 estimated as 0.9961:  log likelihood = -1417,  aic = 2838
\end{verbatim}

Model：\(y_t = \epsilon_t\)

\hypertarget{iv-2}{%
\paragraph{(iv)}\label{iv-2}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot.ts}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS3.fit), }\DataTypeTok{main =} \StringTok{"Residual Series"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{acf}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS3.fit))}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-12-2.pdf}

\hypertarget{comments-3}{%
\paragraph{Comments:}\label{comments-3}}

The residual series seemed to follow a normal distribution with a mean
around 0. The variance are reasonably constant. The plot of ACF of the
residuals showed no problems. All autocorrelation had been modeled.

\hypertarget{v-2}{%
\paragraph{(v)}\label{v-2}}

Other models:

AR(1) AIC = 2839.17, the AR term is not significant MA(1) AIC = 2839.14,
the MA term is not significant

The White Noise model has the smallest AIC (2838).

\hypertarget{ts4}{%
\paragraph{TS4:}\label{ts4}}

\hypertarget{i-3}{%
\paragraph{(i)}\label{i-3}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot.ts}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS4, }\DataTypeTok{main =} \StringTok{"Time Series 4"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-13-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{acf}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS4, }\DataTypeTok{main =} \StringTok{"ACF plot for TS4"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-13-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pacf}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS4, }\DataTypeTok{main =} \StringTok{"PACF plot for TS4"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-13-3.pdf}

\hypertarget{ii-3}{%
\paragraph{(ii)}\label{ii-3}}

Model：\(y_t = \rho_1y_{t-1} + \epsilon_t+ \alpha_1\epsilon_{t-1}\)

The most appropriate model will be ARMA(1, 1). From the series we can
see some clustering and oscillation The plot of ACF showed decay and
PACF also showed decay or some persistence. Since we don't know the
order for the model we can start trying with ARMA(1,1).

\hypertarget{iii-3}{%
\paragraph{(iii)}\label{iii-3}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{TS4.fit =}\StringTok{ }\KeywordTok{arima}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS4, }\DataTypeTok{order =} \KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\NormalTok{TS4.fit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## arima(x = all$TS4, order = c(1, 0, 1))
## 
## Coefficients:
##          ar1     ma1  intercept
##       0.8974  0.9121    -0.0147
## s.e.  0.0139  0.0128     0.5786
## 
## sigma^2 estimated as 0.9828:  log likelihood = -1412.55,  aic = 2833.11
\end{verbatim}

Model：\(y_t = 0.8974y_{t-1} + \epsilon_t + 0.9121\epsilon_{t-1}\)

\hypertarget{iv-3}{%
\paragraph{(iv)}\label{iv-3}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot.ts}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS4.fit), }\DataTypeTok{main =} \StringTok{"Residual Series"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-15-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{acf}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS4.fit))}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-15-2.pdf}

\hypertarget{comments-4}{%
\paragraph{Comments:}\label{comments-4}}

The residual series seemed to follow a normal distribution with a mean
around 0. The variance are reasonably constant. The plot of ACF of the
residuals showed at lag(20) and lag(21) they are slightly significant
but it is not a big problem we can ignore.

\hypertarget{v-3}{%
\paragraph{(v)}\label{v-3}}

Other models:

ARMA(2, 1) AIC = 2833.86, The 2nd AR term is not significant.

ARMA(1, 2) AIC = 2833.73, The 2nd MA term is not significant.

The ARMA(1, 1) model has the smallest AIC and all terms are significant.

\hypertarget{ts5}{%
\paragraph{TS5:}\label{ts5}}

\hypertarget{i-4}{%
\paragraph{(i)}\label{i-4}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot.ts}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS5, }\DataTypeTok{main =} \StringTok{"Time Series 5"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-16-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{acf}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS5, }\DataTypeTok{main =} \StringTok{"ACF plot for TS5"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-16-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pacf}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS5, }\DataTypeTok{main =} \StringTok{"PACF plot for TS5"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-16-3.pdf}

\hypertarget{ii-4}{%
\paragraph{(ii)}\label{ii-4}}

Model：\(y_t = \rho_1y_{t-1} + \epsilon_t+ \alpha_1\epsilon_{t-1}\)

The most appropriate model will be ARMA(1, 1). From the series we can
see strong clustering and some oscillation. The plot of ACF showed decay
and PACF also showed decay. Since we don't know the order for the model
we can start trying with ARMA(1,1).

\hypertarget{iii-4}{%
\paragraph{(iii)}\label{iii-4}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{TS5.fit =}\StringTok{ }\KeywordTok{arima}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS5, }\DataTypeTok{order =} \KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in arima(all$TS5, order = c(1, 0, 1)): possible convergence
## problem: optim gave code = 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{TS5.fit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## arima(x = all$TS5, order = c(1, 0, 1))
## 
## Coefficients:
##          ar1     ma1  intercept
##       0.9674  0.1876    -0.6895
## s.e.  0.0082  0.0260     1.1571
## 
## sigma^2 estimated as 1.063:  log likelihood = -1450.83,  aic = 2909.67
\end{verbatim}

Model：\(y_t = 0.9674 y_{t-1} + \epsilon_t + 0.1876 \epsilon_{t-1}\)

\hypertarget{iv-4}{%
\paragraph{(iv)}\label{iv-4}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot.ts}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS5.fit), }\DataTypeTok{main =} \StringTok{"Residual Series"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-18-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{acf}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS5.fit))}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-18-2.pdf}

\hypertarget{comments-5}{%
\paragraph{Comments:}\label{comments-5}}

The residual series seemed to follow a normal distribution with a mean
around 0. The variance are reasonably constant. But the plot of ACF of
the residuals showed at lag(2) and lag(3) are significant.

\hypertarget{v-4}{%
\paragraph{(v)}\label{v-4}}

Better model:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# ARMA(2, 2)}
\NormalTok{TS5.fit2 =}\StringTok{ }\KeywordTok{arima}\NormalTok{(all}\OperatorTok{$}\NormalTok{TS5, }\DataTypeTok{order =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{2}\NormalTok{))}
\NormalTok{TS5.fit2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## arima(x = all$TS5, order = c(2, 0, 2))
## 
## Coefficients:
##          ar1     ar2     ma1     ma2  intercept
##       0.5840  0.3552  0.6361  0.3235    -0.5989
## s.e.  0.1063  0.1040  0.1014  0.0325     0.9989
## 
## sigma^2 estimated as 0.9954:  log likelihood = -1418.31,  aic = 2848.63
\end{verbatim}

Model：\(y_t = 0.5840 y_{t-1} +0.3552 y_{t-2} + \epsilon_t + 0.6361 \epsilon_{t-1} + 0.3235 \epsilon_{t-2}\)

ARMA(2, 2) AIC = 2848.63

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot.ts}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS5.fit2), }\DataTypeTok{main =} \StringTok{"Residual Series"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-20-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{acf}\NormalTok{(}\KeywordTok{residuals}\NormalTok{(TS5.fit2)) }
\end{Highlighting}
\end{Shaded}

\includegraphics{A4_files/figure-latex/unnamed-chunk-20-2.pdf}

\hypertarget{comments-6}{%
\paragraph{Comments:}\label{comments-6}}

The residual series seemed to follow a normal distribution with a mean
around 0. The variance are reasonably constant. The plot of ACF of the
residuals showed at lag(15) is slightly significant, but it is very weak
so we can ignore it.


\end{document}
